### ISSUE TITLE
Error when parsing positions and line cues that contain text

### ISSUE THREAD

**Issue by andreadev-it** [adracea/rsubs-lib#11]
**Library version:** 0.1.7
**Environment:** WSL2 running under Windows 10
**Current behaviour:** Code panics when parsing a vtt file with a specific formatting

From [the specs](https://www.w3.org/TR/webvtt1/#webvtt-line-cue-setting), the WebVTT format allows to define position and line cues with an optional text parameter, like this:
```
line:90%,end position:50%,center
```

The current code for parsing both the line and position cues will split the cue at the colon, remove the percentage and try to parse the rest as a number. However, having the optional string parameter will lead to a panic, because the code will try to parse `90,end` and `50,center`.
I've tried modifing the code in the `vtt.rs` file at line 421 from
```rust
spos.pos = py.replace('%', "").parse::<i32>().expect("number");
```
to
```rust
spos.pos = py.replace('%', "")
    .split(",")
    .collect::<Vec<&str>>()
    .first()
    .unwrap_or(&"")
    .parse::<i32>().expect("number");
```
and it works.

Of course, this is not the best way to handle the situation (the second value is simply discarded, which is probably an unwanted behaviour). 
I'm a rust noob (the one I'm doing is literally the first project I write in this language) and that's why I didn't fix it and put it as a PR, but I still hope that I've been somewhat helpful 🙂

**Comment by adracea** [comment]
I see this example mentioned in the example above this bit here https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API#webvtt_cues but then lower down the line when they go into details I see no more mentions of this specific style of aligning the text.

I'll try to get a bit of time to look into it as well, but so far I haven't seen any subtitles/captions making use of a bunch of functionality in the standard...mostly because the players don't properly render it 🙄

**Comment by andreadev-it** [comment]
Yes, indeed it seems that they didn't port that possibility inside the MDN...
Thank you a lot for the work you're putting into this!
